Add 0.5 release post
GameDevTecnico/cubos-blog pull request #12
Opened 2024-12-02 19:54 UTC by RiscadoA

2024-12-21 00:28 UTC, SrGesus commented
Is this formatting on AudioSource and AudioListener intended?
![image](https://github.com/user-attachments/assets/f6962fb4-95da-48b6-a05a-e62cdf313c48)

2025-01-11 10:27 UTC, NunoBaptista57 requested changes
review test

2025-01-11 10:27 UTC, NunoBaptista57 commented on content/0-5.rst
> +It wasn't very convenient to have only a toogle to control the Debug Camera, so we added a hold mode.
```suggestion
Previously, arranging assets in the scene required a debug camera. This system worked by locking the camera to the mouse with a toggle, which made it inconvenient. With the hold mode, instead of activating the camera and then moving it, the user can simply move it while holding a key.
```

2025-01-11 10:27 UTC, NunoBaptista57 commented on content/0-5.rst
> +TODO: explain feature and why it is useful
```suggestion
```

2025-01-11 10:27 UTC, NunoBaptista57 commented on content/0-5.rst
> +Editor Feature 1 :dim:`(@Author1)`
```suggestion
```

2025-01-11 11:06 UTC, NunoBaptista57 requested changes

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +Sub-title for this feature
```suggestion
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +TODO: more explaining
```suggestion

```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +So now there are two simple new methods - ``save(path, indentation)`` and
```suggestion
Now there are two new clearer methods - ``save(path, indentation)`` and
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +Another great addition to the CUBOS engine was the support for text rendering in the UI, this will greatly improve the capabilities
```suggestion
A significant addition to the CUBOS engine was the support for text rendering in the UI, this will greatly improve the capabilities 
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +Allow identifying assets in code from their path :dim:`(@GalaxyCrush)`
```suggestion
Enable assets to be identified in the code by their file path :dim:`(@GalaxyCrush)`
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +We noticed that in some samples, the shadows had some shadow acne and/or peter panning artifacts. So, to improve it, we implemented the option of using the Shadow Normal Offset Bias algorithm, which
insert links to the terms definitions
shadow acne
https://digitalrune.github.io/DigitalRune-Documentation/html/3f4d959e-9c98-4a97-8d85-7a73c26145d7.htm#Acne
peter panning
https://digitalrune.github.io/DigitalRune-Documentation/html/3f4d959e-9c98-4a97-8d85-7a73c26145d7.htm#PeterPanning

if you find better sources, use them instead

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +The physics solver had some constants that were hardcoded, which made it difficult to change them. Now we have a resource that allows the user to easily configure these constants.
```suggestion
The physics solver previously included hardcoded constants, which were not easily accessible or modifiable. With the introduction of configurable variables, developers now can control and adjust the physics solver more effectively.
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +Previously, our `CMake <https://cmake.org/>`_ build configuration, while functional, was really incomplete in terms of features and was also extremely messy.
```suggestion
Previously, while functional, our `CMake <https://cmake.org/>`_ build configuration, was incomplete in terms of features and poorly organized.
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +With the engine becoming more and more fleshed out, we started wanting to be able to install the engine as a library system-wide, so that we could use it in other projects
```suggestion
As the engine evolved, we recognized the need to install it as a system-wide library for use in other projects.
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +Before, we always simply added the engine repository as a ``git`` submodule in our projects, but this meant having one copy locally of the whole codebase for each project, which was not ideal.
```suggestion
Before, we added the engine repository as a ``git`` submodule in our projects, which required maintaining a local copy of the entire codebase for each project — an inefficient approach.
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +So, we decided to clean up the CMake configuration, and add installation and ``find_package`` support. In pratice, this means that you can now install the whole Cubos project, and to use it in anothe
```suggestion
To address this, we decided to clean up the CMake configuration, and add installation and ``find_package`` support.  As a result, you can now install the entire Cubos project, and to use it in another project, you only need to include the following lines in your ``CMakeLists.txt``:
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +We've had a PR open since 0.2 for porting Cubos to the web with `Emscripten <https://emscripten.org/>`_, but it was constantly postponed due to some issues still being present, and the fact that we w
```suggestion
We've had a pull request open since 0.2 for porting Cubos to the web with `Emscripten <https://emscripten.org/>`_, but it was constantly postponed due to some issues still being present, and the fact that we were focusing on other features.
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +Now, we finally made the final push to get it working, and now Cubos can be compiled to WebAssembly and run in the browser!
```suggestion
We have now completed the final steps to enable Cubos to be compiled to WebAssembly, allowing it to run in the browser.
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +We think this is an important feature, as for game jams, for example, it's very useful to be able to share your game with others without them having to download anything, and also to be able to play
```suggestion
This is an important feature, as for game jams, for example, it's handy to share your game with others without them having to download anything, and also to be able to play it on any device.
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +We also think it's a good way to showcase the engine to people who might be interested in using it, but don't want to download it.
```suggestion
It's also a good way to showcase the engine to people who might be interested in using it, but don't want to download it.
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +One of the major challenges was guaranteeing compatibility with WebGL2. Fortunately, the whole rendering code is built on top of a rendering API abstraction layer.
```suggestion
One of the major challenges was guaranteeing compatibility with WebGL2. Fortunately, the rendering code is built on top of a rendering API abstraction layer.
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +One big advantage of this is that we can now also install Quadrados and Tesseratos, the tools we use for making games with Cubos, system-wide, as you would with any other application.
```suggestion
One big advantage is that we can now install Quadrados and Tesseratos, the tools we use for making games with Cubos, system-wide, as you would with any other application.
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +so that in the next update we can trace them back. This information consists of identifiers for each collision manifold and the corrections applied to each contact point. Due to limitations in the cu
```suggestion
so that in the next update we can trace them back. This information includes identifiers for each collision manifold and the corrections applied to each contact point. Due to limitations in the current implementation of 
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +We noticed that in some samples, the shadows had some shadow acne and/or peter panning artifacts. So, to improve it, we implemented the option of using the Shadow Normal Offset Bias algorithm, which
```suggestion
We noticed that the shadows had some shadow acne and/or peter panning artifacts in some samples. So, to improve it, we implemented the option of using the Shadow Normal Offset Bias algorithm, which improved the quality of the shadows and reduced these artifacts. To use the algorithm, the user simply has to assign a value to the normalOffsetScale field in the light casters `ShadowCaster  <https://docs.cubosengine.org/structcubos_1_1engine_1_1ShadowCaster.html>`_.
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +This new features includes and `uiTextPlugin` that can be added wich contains the `UIText` component, this one contains all the data needed
```suggestion
This new feature includes an `uiTextPlugin` that can be added which contains the `UIText` component, this one contains all the data needed
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +Below is a screenshot of the sample with all light types casting shadows. Some tweaks have been done to better highlight the shadows.
```suggestion
Below is a screenshot of the sample with all light types casting shadows. Some tweaks have been done to highlight the shadows better.
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +You may want to read the previous blog posts for more detailed information on this.
```suggestion
You can read the previous blog posts for more detailed information.
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +renderer, starting with spot light shadows, and then directional ones. Naturally, the next step was to
```suggestion
renderer, starting with spotlight shadows, and then directional ones. Naturally, the next step was to
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +Over the past couple releases, **shadows** have been gradually introduced to the engine's graphics
```suggestion
Over the past couple of releases, **shadows** have been gradually introduced to the engine's graphics
```

2025-01-11 11:06 UTC, NunoBaptista57 commented on content/0-5.rst
> +all directions, there are actually 6 atlas textures, one for each direction of a cube.
```suggestion
all directions, there are 6 atlas textures, one for each direction of a cube.
```

2025-01-11 11:13 UTC, NunoBaptista57 requested changes

2025-01-11 11:13 UTC, NunoBaptista57 commented on content/0-5.rst
> +In the next release, which should be out by **TODO WHEN**, we're planning to work on the following features:
```suggestion
In the next release, which should be out by February <sup>6</sup>, we're planning to work on the following features:
```

2025-01-11 11:34 UTC, DiogoMendonc-a requested changes

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +It wasn't very convenient to have only a toogle to control the Debug Camera, so we added a hold mode.
How is toggle inconvenient? How does the hold mode solve that?

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +Editor Feature 1 :dim:`(@Author1)`
Forgot to remove a placeholder

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +This blog post covers the most important changes, but you can check out the full changelog in our `repository <https://github.com/GameDevTecnico/cubos/blob/main/CHANGELOG.md>`_.
More of a suggestion than a review, should we add a very simple "this version in a sentence" to sum up the post?

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +implement shadows for point lights, finally completing support for all types of lights.
```suggestion
implement shadows for point lights, finally completing support for the most common types of lights.
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +Once again, point shadows are enabled by adding a component to the light entity, this time a
I'd avoid writing using phrasal modifiers which antecedents are on previous posts. "Once again" and "this time" sound weird if you haven't read very recently the other releases.

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +They behave similarly to spot shadows, lacking all the configurable values of the more complex directional shadows.
re: my previous comment, This reference to spot shadows is fine. It was already established they were on a different release, and this introduces a point of reference for those familiar with past releases.

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +You may want to read the previous blog posts for more detailed information on this.
A link would be nice

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +The final result of shadows can be seen in the `Shadows sample <https://github.com/GameDevTecnico/cubos/tree/main/engine/samples/render/shadows>`_.
```suggestion
The final result of our shadows engine can be seen in the `Shadows sample <https://github.com/GameDevTecnico/cubos/tree/main/engine/samples/render/shadows>`_.
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +.. image:: images/0.5/shadows_sample.png
Shouldn't we use a scene with a lot less ambient light? There's not a lot of contrast in there.

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +With the plugin, you can now register listeners, and control audio sources with play, pause, and stop functionality. You can also customize audio playback by modifying the ``AudioSource`` properties
```suggestion
With the plugin you can now register listeners and control audio sources with play, pause, and stop functionality. You can also customize audio playback by modifying the ``AudioSource`` properties for each entity, adjusting settings such as volume, pitch, and looping behavior to tailor the sound to your needs.
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +Sub-title for this feature
Placeholder, please remove

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +Some way to interact with the files of the ``Settings`` resource was missing,
```suggestion
The ``Settings`` resource was missing some way to interact with its files,
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +there was only a startupSystem that would load the file from a command line
```suggestion
as it was limited to a startup system that would load the file from a command line
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +argument and then no way for changes to persist which was a bit inconvenient.
```suggestion
argument with no way for posterior changes to persist which was inconvenient.
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +So now there are two simple new methods - ``save(path, indentation)`` and
```suggestion
Now there are two new simple methods - ``save(path, indentation)`` and
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +Anti-aliasing using FXAA technique :dim:`(@kuukitenshi)`
for grammatical consistency with the text.
```suggestion
Anti-aliasing using the FXAA technique :dim:`(@kuukitenshi)`
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +As you can see in the images below, the FXAA smooths out the visuals without the performance cost of traditional anti-aliasing methods.
Here, it's used as subject, so no need for the "the"
```suggestion
As you can see in the images below, FXAA smooths out the visuals without the performance cost of traditional anti-aliasing methods.
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +Another great addition to the CUBOS engine was the support for text rendering in the UI, this will greatly improve the capabilities
```suggestion
Another great addition to the CUBOS engine was the support for text rendering in the UI, which will greatly improve the capabilities 
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +This new features includes and `uiTextPlugin` that can be added wich contains the `UIText` component, this one contains all the data needed
```suggestion
This new feature comes in the `uiTextPlugin`, which includes the `UIText` component, containing all the data needed
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +- **Font**: represents a font to be that can be used to create font atlases (.ttf and .otf supported).
```suggestion
- **Font**: holds the raw font data to be used to create font atlases (.ttf and .otf files supported).
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +- **FontAtlas**: atlas created from a given font with different configurable properties.
```suggestion
- **FontAtlas**: maps characters to their glyph on a given font, with different configurable properties. 
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +**Note:** Currently only the ASCII charset is supported, UTF-8 support will be worked on in a future release.
```suggestion
**Note:** Currently only the ASCII charset is supported, UTF-8 support will be added in a future release.
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +Assets could only be identified by their UUID, which could sometimes be confusing when working with multiple assets.
```suggestion
Assets could only be identified by their UUID, which can be hard to keep track of for human developers.
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +Now, they are able to be identified by their path, thus allowing for better compression when developing projects with CUBOS.
```suggestion
Now, they are able to be identified by their path, thus making them easier to handle when developing projects with CUBOS.
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +We noticed that in some samples, the shadows had some shadow acne and/or peter panning artifacts. So, to improve it, we implemented the option of using the Shadow Normal Offset Bias algorithm, which
```suggestion
We noticed that in some samples, the shadows had some shadow acne and/or peter panning artifacts. To reduce this, we implemented the option of using the Shadow Normal Offset Bias algorithm, which improves the quality of the shadows and reduces these artifacts. To use the algorithm, the user simply has to assign a value to the normalOffsetScale field in the `ShadowCaster  <https://docs.cubosengine.org/structcubos_1_1engine_1_1ShadowCaster.html>`_.
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +Below is a screenshot of the sample with all light types casting shadows. Some tweaks have been done to better highlight the shadows.
Disagree

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +Previously, our `CMake <https://cmake.org/>`_ build configuration, while functional, was really incomplete in terms of features and was also extremely messy.
To build on @NunoBaptista57 suggestions,
```suggestion
While functional, our `CMake <https://cmake.org/>`_ build configuration was incomplete in terms of features and poorly organized.
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +One big advantage of this is that we can now also install Quadrados and Tesseratos, the tools we use for making games with Cubos, system-wide, as you would with any other application.
Disagree

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +We've had a PR open since 0.2 for porting Cubos to the web with `Emscripten <https://emscripten.org/>`_, but it was constantly postponed due to some issues still being present, and the fact that we w
```suggestion
We've had a PR open since 0.2 for porting Cubos to the web with `Emscripten <https://emscripten.org/>`_, but it was constantly postponed due to some blocking issues being present, and us being focused on other features.
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +Now, we finally made the final push to get it working, and now Cubos can be compiled to WebAssembly and run in the browser!
Alternatively, to keep the tone at the cost of formality.
```suggestion
Now, we finally made the final push to get it working, and Cubos can be compiled to WebAssembly and ran in the browser!
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +We also think it's a good way to showcase the engine to people who might be interested in using it, but don't want to download it.
No one in their right minds would ever not want to download Cubos. They are merely reasonably cautious.
```suggestion
We also think it's a good way to showcase the engine to people who might be interested in using it, but are reluctant to download it.
```

2025-01-11 11:34 UTC, DiogoMendonc-a commented on content/0-5.rst
> +In the next release, which should be out by **TODO WHEN**, we're planning to work on the following features:
Not how dates are formatted.
```suggestion
In the next release, which should be out by February 6th, we're planning to work on the following features:
```

2025-01-12 12:55 UTC, tomas7770 commented on content/0-5.rst
> +.. image:: images/0.5/shadows_sample.png
Even setting the ambient light to 0 doesn't seem to help much, but some renderer fixes in the `demo-hotfixes` branch made it a lot better IMO. Maybe we could use that?

2025-01-27 15:15 UTC, merged