Add 0.2 & CoffeJam blogpost
GameDevTecnico/cubos-blog pull request #8
Opened 2024-05-07 18:58 UTC by roby2014

Every member that contributed with new features should write-up something simple but descriptive of the new feature (images, usage, technical information, ...).

Stuff to talk about/showcase:
- [x] Observers, show callback-like behavior (@RiscadoA).
- [x] Repeating systems and fixed-step updates (@joaomanita).
- [x] New plugin scheme, dependency specification (@RiscadoA).
- [x] World inspector upgrades - ChildOf hierarchy and search bar (@diogomsmiranda).
- [x] New rendering plugins, optimizations made (@RiscadoA, @tomas7770).
- [x] Transform gizmo enhancements - constant scale and rotation controls (@DiogoMendonc-a).
- [x] New physics solver, show new complex sample (@fallenatlas).
- [x] Sub-scene importing in scene editor (@teres4).
- [x] Replaced all old serialization code by proper reflection (@Dacops).

2024-05-19 11:05 UTC, DiogoMendonc-a requested changes
Minor grammar nitpicks, mostly

2024-05-19 11:05 UTC, DiogoMendonc-a commented on content/0-2-and-coffeejam.rst
> +The World inspector as been on our radar for quite some time now, as a tool that could be improved.
```suggestion
The World inspector has been on our radar for quite some time now as a tool that could be improved.
```

2024-05-19 11:05 UTC, DiogoMendonc-a commented on content/0-2-and-coffeejam.rst
> +* Making it easier to find the entities you are looking for.
```suggestion
* Making it easier to find the entities you are looking for;
```

2024-05-19 11:05 UTC, DiogoMendonc-a commented on content/0-2-and-coffeejam.rst
> +To tackle the first point I've added a search bar that allows you to filter the entities in the scene, either by their name, or by their components. i.e:
```suggestion
To tackle the first point we've added a search bar that allows you to filter the entities in the scene, either by their name, or by their components. i.e:
```
Should we always use the plural, for consistency?

2024-05-19 11:05 UTC, DiogoMendonc-a commented on content/0-2-and-coffeejam.rst
> +To tackle the first point I've added a search bar that allows you to filter the entities in the scene, either by their name, or by their components. i.e:
```suggestion
To tackle the first point I've added a search bar that allows you to filter the entities in the scene, either by their name or by their components. e.g.:
```

2024-05-19 11:05 UTC, DiogoMendonc-a commented on content/0-2-and-coffeejam.rst
> +* Getting more information about the entities in the scene.
```suggestion
* Displaying more information about the entities in the scene.
```

2024-05-19 11:05 UTC, DiogoMendonc-a commented on content/0-2-and-coffeejam.rst
> +Our focus on this release was to continue working on improving and implementing base functionality, such as rendering and physics, and also to improve on the tools available to the developer.
Shouldn't this be at the top?

2024-05-19 11:05 UTC, DiogoMendonc-a commented on content/0-2-and-coffeejam.rst
> +This update we introduced the ``Solver``, which works to satisfy the physics constraints applied to entities (eg. Spring, Fixed distance between entities, etc.).
```suggestion
This update we introduced the ``Solver``, which works to satisfy the physics constraints applied to entities (e.g. Spring, Fixed distance between entities, etc.).
```

2024-05-19 11:05 UTC, DiogoMendonc-a commented on content/0-2-and-coffeejam.rst
> +`Serialization <https://gamedevtecnico.github.io/cubos/docs/group__core-data-ser.html>`_ is a crucial part of the game engine that allows for the saving of any CUBOS. game components as well as then
```suggestion
`Serialization <https://gamedevtecnico.github.io/cubos/docs/group__core-data-ser.html>`_ is a crucial part of the game engine that allows for the saving of any CUBOS game components as well as then loading them in.
```

2024-05-19 11:05 UTC, DiogoMendonc-a commented on content/0-2-and-coffeejam.rst
> +Previously, serialization was done through a series of functions, both for reading and writing that could be overloaded for each type.
```suggestion
Previously, serialization was done through a series of functions, both for reading and writing, that could be overloaded for each type.
```

2024-05-19 14:41 UTC, RiscadoA commented
Just missing an image/GIF for the scene editor (@teres4) and world inspector (@diogomsmiranda).
Also, @fallenatlas could you take increase the physics sample gif size? It is a tad smaller than the other embedded stuff which looks a little weird.

2024-05-21 17:25 UTC, DiogoMendonc-a approved these changes

2024-05-21 17:49 UTC, merged